name: spotify_neumorphic
description: Spotify Neumorphism UI Redesign.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lint: ^1.5.3
  fluttertoast: ^8.0.6
  cupertino_icons: ^1.0.2
  palette_generator: ^0.3.0
  flutter_neumorphic: ^3.1.0
  font_awesome_flutter: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/genres/
    - assets/images/welcome/
    - assets/images/recently_played/
    - assets/images/playlists_flow/
    - assets/json/

  fonts:
    - family: helvetica
      fonts:
      - asset: assets/fonts/Helvetica-Bold.ttf
      - asset: assets/fonts/Helvetica-BoldOblique.ttf
      - asset: assets/fonts/Helvetica-Compressed.otf
      - asset: assets/fonts/Helvetica-Oblique.ttf
      - asset: assets/fonts/Helvetica.ttf
    - family: helvetica-rounded
      fonts:
      - asset: assets/fonts/Helvetica-Rounded-Bold.otf